# Generated by Django 3.2.22 on 2023-11-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waw_blog', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
