# Generated by Django 3.2.22 on 2023-12-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waw_blog', '0004_auto_20231112_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activity',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='getting_there',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='travel_advice',
            field=models.TextField(default=''),
        ),
    ]
