# Generated by Django 3.2.22 on 2023-12-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waw_blog', '0006_auto_20231207_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
